uuid = "86faac93-6295-4759-8fce-aa5cef636425"
name = "Generate M3U playlist"
version = "0.1.1"
authors = ['MusicBrainz Contributors']
description = "Generates M3U playlist files after saving music files."
categories = ['other']
homepage = "https://github.com/musicbrainz/picard-plugins/tree/2.0/plugins/playlist"
report_bugs_to = "https://github.com/musicbrainz/picard-plugins/tree/2.0/plugins/playlist"
api = ["3.0"]
license = "GPL-2.0-or-later"
license_url = "https://www.gnu.org/licenses/gpl-2.0.html"
